name: Call tests builder

on:
  push:

jobs:
  version:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/hello-world-docker-action@v2
        with:
          who-to-greet: 'Mona the Octocat'
